language: java

jdk:
 - oraclejdk7

language: python

python:
 - "3.4"

notifications:
  email: false

install:
 - redis-server > /dev/null 2>&1 &
 - sudo apt-get install python-pip npm nodejs
 - sudo pip install virtualenv
 - virtualenv qabel-drop
 - source qabel-drop/bin/activate
 - pip install -r qabel-drop/requirements.txt
 - virtualenv --python=python3.4 qabel-accounting
 - source qabel-accounting/bin/activate
 - pip install -r qabel-accounting/requirements.txt

script:
 - travis_wait ./gradlew check
