sudo: false

language: python

python:
 - "3.4"

cache: pip

language: python

python:
 - "3.4"

notifications:
  email: false

services:
  - redis-server

install:
 - pip install -r qabel-drop/requirements.txt
 - virtualenv --python=python3.4 qabel-accounting
 - source qabel-accounting/bin/activate
 - pip install -r qabel-accounting/requirements.txt

script:
 - ./gradlew check
